CSCwa43372 - Adding Support for file uploads via rest API
ciscoecosystem/aci-go-client pull request #225
Opened 2022-07-11 20:23 UTC by phdawson

Creating DoBig function to allow client to accept and send incomplete payloads. This will be used for uploading images to the APIC firmware repository in chunks.

2022-07-13 23:28 UTC, jjagadis commented on client/client.go
> +                fmt.Println("big req resp" , bodyStr)
Please remove this

2022-07-14 03:04 UTC, sajagana commented
Please fix the formatting issue with "gofmt".

2022-07-14 14:31 UTC, jjagadis commented on client/client.go
> +	// or go home (?)
Do you plan to keep this comment ?

2022-07-14 14:33 UTC, jjagadis commented on client/client.go
> +				log.Printf("[DEBUG] Exit from Do method")
Multiple log statement have "Do method", good idea to change the log to match function name

2022-07-14 15:38 UTC, xinyuezhao requested changes

2022-07-14 15:38 UTC, xinyuezhao commented on client/client.go
> +			//obj, err := container.ParseJSON(bodyBytes)
may want to remove this line if not needed

2022-07-14 15:38 UTC, xinyuezhao commented on client/client.go
> +				//obj, err := container.ParseJSON(bodyBytes)
may want to remove this line if not needed

2022-07-28 20:14 UTC, lhercot commented
As we have solved this issue with adding a condition in the existing methods in case retries = 0, I am closing this PR.

2022-07-28 20:14 UTC, closed without merging