[bugfix] preserve state of skipLoggingPayload in the client Authentic…
ciscoecosystem/aci-go-client pull request #256
Opened 2023-02-01 13:14 UTC by akinross

…ate method

2023-02-01 14:43 UTC, lhercot requested changes

2023-02-01 14:43 UTC, lhercot commented on client/client.go
> +	c.skipLoggingPayload = false
```suggestion

```

2023-02-01 15:04 UTC, akinross commented on client/client.go
> +//	for encoding/decoding
yes

2023-02-01 17:36 UTC, anvitha-jain requested changes

2023-02-01 17:36 UTC, anvitha-jain commented on client/client.go
> +//	for encoding/decoding
If these are two different sentences, can it start with capital letter and with a full stop?

2023-02-01 20:20 UTC, shrsr commented
LGTM

2023-02-02 09:37 UTC, lhercot approved these changes
LGTM

2023-02-02 09:38 UTC, merged