Add clients and models for cloud service EPG
ciscoecosystem/aci-go-client pull request #281
Opened 2023-08-16 18:03 UTC by gmicol

2023-08-17 01:50 UTC, sajagana requested changes

2023-08-17 01:50 UTC, sajagana commented on models/cloud_svc_epg.go
> +	CloudServiceEPg_type string `json:",omitempty"`
Please check the `exceptionTag` is required.

2023-08-17 01:50 UTC, sajagana commented on models/cloud_svc_epg.go
> +	A(cloudSvcEPgMap, "CloudServiceEPg_type", cloudSvcEPg.CloudServiceEPg_type)
```suggestion
	A(cloudSvcEPgMap, "type", cloudSvcEPg.CloudServiceEPg_type)
```

Is it CloudServiceEPg_type or type?

2023-08-17 01:50 UTC, sajagana commented on models/cloud_svc_epg.go
> +			CloudServiceEPg_type: G(CloudServiceEPgCont, "CloudServiceEPg_type"),
```suggestion
			CloudServiceEPg_type: G(CloudServiceEPgCont, "type"),
```
Is it CloudServiceEPg_type or type?

2023-08-17 07:02 UTC, gmicol commented on models/cloud_svc_epg.go
> +	A(cloudSvcEPgMap, "CloudServiceEPg_type", cloudSvcEPg.CloudServiceEPg_type)
you are right. it is "type".

2023-08-17 07:02 UTC, gmicol commented on models/cloud_svc_epg.go
> +			CloudServiceEPg_type: G(CloudServiceEPgCont, "CloudServiceEPg_type"),
same thing here: it is "type".

2023-08-17 07:16 UTC, gmicol commented on models/cloud_svc_epselector.go
> +	NameAlias       string `json:",omitempty"`
I do not find any of these attributes in the go-client repo, even for other class objects that do require them.

I know we automatically get these attributes in the payload for Ansible ACI but what about the go-client and terraform? @lhercot

2023-08-21 06:34 UTC, sajagana approved these changes
LGTM!

2023-08-21 17:49 UTC, akinross approved these changes
LGTM

2023-08-22 00:20 UTC, shrsr approved these changes
LGTM

2023-08-24 17:39 UTC, lhercot approved these changes
LGTM

2023-08-24 17:42 UTC, merged