Added GetMORnPrefix to extract Rn string from Dn
ciscoecosystem/aci-go-client pull request #283
Opened 2023-09-12 06:44 UTC by sajagana

2023-09-12 07:51 UTC, akinross approved these changes
LGTM

2023-09-12 13:26 UTC, shrsr requested changes

2023-09-12 13:26 UTC, shrsr commented on models/util.go
> +func GetMORnPrefix(dn string) string {
Does this function work for Rns containing '/'?

2023-09-12 13:41 UTC, shrsr commented on models/util.go
> +func GetMORnPrefix(dn string) string {
![Screenshot 2023-09-12 at 9 40 44 AM](https://github.com/ciscoecosystem/aci-go-client/assets/23535091/bba0a3f4-8e3e-4b2a-9e3e-76c9c23c97e0)

2023-09-14 11:20 UTC, shrsr approved these changes
LGTM

2023-09-14 14:43 UTC, merged