Add ESG
ciscoecosystem/aci-go-client pull request #70
Opened 2021-02-26 17:26 UTC by xinyuezhao

- add fv_e_sg.go
- add fvESg_service.go

2021-04-06 10:08 UTC, AshuSoni-crest commented on client/fvESg_service.go
> +				"dn": "%s"
We usually add "annotation" parameter in the attributes payload with value as "orchestrator:terraform" if relation class support annotation.

2021-04-06 10:08 UTC, AshuSoni-crest commented on client/fvESg_service.go
> +				"dn": "%s"
We usually add "annotation" parameter in the attributes payload with value as "orchestrator:terraform" if relation class support annotation.

2021-04-06 10:09 UTC, AshuSoni-crest commented on client/fvESg_service.go
> +				"dn": "%s"
We usually add "annotation" parameter in the attributes payload with value as "orchestrator:terraform" if relation class support annotation.

2021-04-06 10:09 UTC, AshuSoni-crest commented on client/fvESg_service.go
> +				"dn": "%s","tnQosCustomPolName": "%s"
We usually add "annotation" parameter in the attributes payload with value as "orchestrator:terraform" if relation class support annotation.

2021-04-06 10:09 UTC, AshuSoni-crest commented on client/fvESg_service.go
> +				"dn": "%s"
We usually add "annotation" parameter in the attributes payload with value as "orchestrator:terraform" if relation class support annotation.

2021-04-06 10:09 UTC, AshuSoni-crest commented on client/fvESg_service.go
> +				"dn": "%s","tnFvCtxName": "%s"
We usually add "annotation" parameter in the attributes payload with value as "orchestrator:terraform" if relation class support annotation.

2021-04-06 10:10 UTC, AshuSoni-crest commented on client/fvESg_service.go
> +				"dn": "%s"
We usually add "annotation" parameter in the attributes payload with value as "orchestrator:terraform" if relation class support annotation.

2021-04-06 10:10 UTC, AshuSoni-crest commented on client/fvESg_service.go
> +				"dn": "%s"
We usually add "annotation" parameter in the attributes payload with value as "orchestrator:terraform" if relation class support annotation.

2021-04-06 10:12 UTC, AshuSoni-crest requested changes
some changes needed. Added comments in files

2021-04-15 21:28 UTC, lhercot approved these changes

2021-04-15 21:30 UTC, merged