[vmmDomP] Added classes to configure childern and relationship for vmmDomP class #175
ciscoecosystem/aci-go-client pull request #77
Opened 2021-03-10 02:36 UTC by anvitha-jain

Solves issue #175

2021-04-06 09:59 UTC, AshuSoni-crest commented on client/vmmCtrlrP_service.go
> +				"tnFvnsMcastAddrInstPName": "%s"
We usually add "annotation" parameter in the attributes payload with value as "orchestrator:terraform" if relation class support annotation.

2021-04-06 09:59 UTC, AshuSoni-crest commented on client/vmmCtrlrP_service.go
> +				"tDn": "%s"
We usually add "annotation" parameter in the attributes payload with value as "orchestrator:terraform" if relation class support annotation.

2021-04-06 09:59 UTC, AshuSoni-crest commented on client/vmmCtrlrP_service.go
> +				"dn": "%s"
We usually add "annotation" parameter in the attributes payload with value as "orchestrator:terraform" if relation class support annotation.

2021-04-06 09:59 UTC, AshuSoni-crest commented on client/vmmCtrlrP_service.go
> +
We usually add "annotation" parameter in the attributes payload with value as "orchestrator:terraform" if relation class support annotation.

2021-04-06 10:00 UTC, AshuSoni-crest commented on client/vmmCtrlrP_service.go
> +
We usually add "annotation" parameter in the attributes payload with value as "orchestrator:terraform" if relation class support annotation.

2021-04-06 10:00 UTC, AshuSoni-crest commented on client/vmmCtrlrP_service.go
> +
We usually add "annotation" parameter in the attributes payload with value as "orchestrator:terraform" if relation class support annotation.

2021-04-06 10:01 UTC, AshuSoni-crest commented on client/vmmUsrAccP_service.go
> +
Remove these extra lines

2021-04-06 10:01 UTC, AshuSoni-crest commented on client/vmmVSwitchPolicyCont_service.go
> +				"samplingRate": "%s"
We usually add "annotation" parameter in the attributes payload with value as "orchestrator:terraform" if relation class support annotation.

2021-04-06 10:01 UTC, AshuSoni-crest commented on client/vmmVSwitchPolicyCont_service.go
> +				"tDn": "%s"
We usually add "annotation" parameter in the attributes payload with value as "orchestrator:terraform" if relation class support annotation.

2021-04-06 10:02 UTC, AshuSoni-crest commented on client/vmmVSwitchPolicyCont_service.go
> +				"tDn": "%s"
We usually add "annotation" parameter in the attributes payload with value as "orchestrator:terraform" if relation class support annotation.

2021-04-06 10:02 UTC, AshuSoni-crest commented on client/vmmVSwitchPolicyCont_service.go
> +				"tDn": "%s"
We usually add "annotation" parameter in the attributes payload with value as "orchestrator:terraform" if relation class support annotation.

2021-04-06 10:02 UTC, AshuSoni-crest commented on client/vmmVSwitchPolicyCont_service.go
> +				"tDn": "%s"
We usually add "annotation" parameter in the attributes payload with value as "orchestrator:terraform" if relation class support annotation.

2021-04-06 10:02 UTC, AshuSoni-crest commented on client/vmmVSwitchPolicyCont_service.go
> +				"tDn": "%s"
We usually add "annotation" parameter in the attributes payload with value as "orchestrator:terraform" if relation class support annotation.

2021-04-06 10:02 UTC, AshuSoni-crest commented on client/vmmVSwitchPolicyCont_service.go
> +				"tDn": "%s"
We usually add "annotation" parameter in the attributes payload with value as "orchestrator:terraform" if relation class support annotation.

2021-04-06 10:02 UTC, AshuSoni-crest commented on client/vmmVSwitchPolicyCont_service.go
> +				"tDn": "%s"
We usually add "annotation" parameter in the attributes payload with value as "orchestrator:terraform" if relation class support annotation.

2021-04-06 10:05 UTC, AshuSoni-crest commented on models/vmm_v_switch_policy_cont.go
> +}
reformatting is needed for this file

2021-04-06 10:06 UTC, AshuSoni-crest requested changes
Some changes needed. Added comments in the files

2021-04-15 21:35 UTC, lhercot approved these changes

2021-04-15 21:36 UTC, merged